### ISSUE TITLE
開催予定のイベントをdiscordチャンネルに通知したい

### ISSUE THREAD

**Issue by Saki-htr** [teacherteacher-jp/manabiya#106]
# ToDo
- [x] discord通知の時間、送る内容を決める
- [x] 調査して実装イメージを固める

# 備忘
- [x] productionへのcredentialsの追加
- [x] 本番環境で投稿させたいチャンネルに投稿できるか要確認
- [ ] herokuスケジューラーで定期実行ジョブを2つ追加
  - [ ] 毎日： `rails runner "Event.new.notify_upcoming_events"`
  - [ ] 毎週： `rails runner "Event.new.XXX"`

**Comment by Saki-htr** [comment]
# discord通知の実装方法を調査する

**Comment by Saki-htr** [comment]
## すでにdiscord通知をしてる実装があるのでそこを読む

- すでにManabiyaからdiscordに通知してる仕組みがある。
  - 明日のボランティアのメンバーのお知らせや、プロフィール登録した時の通知など。
- https://github.com/teacherteacher-jp/manabiya/blob/main/app/models/notification.rb に、通知処理してるメソッド があるので、ここにメソッド追加すればよさそう。

**Comment by Saki-htr** [comment]
## イベントがcreateされたタイミングでdiscord通知の実装できた

- 検証しやすいので作成成功したタイミングでイベント通知させる実装を小さく作った

作成したイベント
![image](https://github.com/user-attachments/assets/c73a784a-8286-4c20-bbf0-5f261224f3cc)

- 実際の通知

<img width="883" alt="image" src="https://github.com/user-attachments/assets/9c10f164-eff6-4003-a44a-bc9344a53868">

**Comment by Saki-htr** [comment]
# 大まかな実装イメージは掴めたので、discord通知の「時間」と「送る内容」を決める

**Comment by Saki-htr** [comment]
junebokuさんからのフィードバック

> 全体的に、よく考えられていて「よさそう〜」と感じました
- 毎日、の方
  - 「今日・明日・明後日の分」くらいでもいいかな〜とは思った
  - いうて、そんなに膨大な量にはならないだろうってのと「ああ、明日か！」と気付くパティーンがありそうで
- 毎週日曜日、の方
  - よさそう
- 加えて
  - Event after_create も ⁠📅｜イベント情報 に通知しちゃってよさそう

たしかに、1日に開催されるイベント数は少ない(多くても2個くらい)で、明日明後日のイベント情報も通知される方が、「それ忘れてたけど明日ならスケジュール調整可能!」ってこともあり得そうなので、今日〜2日後までのイベント情報の通知がよさそう!
イベントが作成されたこと自体も通知があった方が気付きやすい&盛り上がるので入れた方がよさそう。


## 決定版

通知先は全部、イベント情報チャンネル

### 毎日その日開催のイベント情報を通知
- 通知時間：毎日朝6時
- 内容：**今日・明日・明後日**開催予定のイベント情報

### 毎週日曜に、次の1週間のイベント情報を通知
- 通知時間： 日曜朝8時
- 内容：次の1週間(月〜日)開催予定のイベント情報

### イベントが作成された(after_create)のタイミングで通知
- 通知時間： create後
- 内容：作成されたイベント

**Comment by Saki-htr** [comment]
# 細かい文言はレビュー依頼してから詰めた方が効率的なので、実装を進めていく!

**Comment by Saki-htr** [comment]
通知することは成功

**Comment by Saki-htr** [comment]
## 定期実行で通知させる処理を調べる

**Comment by Saki-htr** [comment]
## credentialsにスレッドidを追加して通知を動かしたら、 create後にイベント通知されなくなったので調べる

**Comment by Saki-htr** [comment]
コンソールで以下を実行したら、ちゃんとdiscordに通知された
```ruby
Notification.new.notify_event_created(@event)
```

**Comment by Saki-htr** [comment]
### 解決： credentials のファイルを変更した後 bin/devし直してなかった。し直して最新のcredentialsを読み込ませたらアプリケーション上で通知された.

**Comment by Saki-htr** [comment]
## 本番環境はherokuで動いてるので、定期実行させる方法を調べる

- [ ] https://devcenter.heroku.com/ja/articles/scheduler 読む
- [ ]`rails runner`の使い方調べる

**Comment by Saki-htr** [comment]
### herokuとrails runnerで定期実行させるためにやったこと記録

- `heroku addons:create scheduler:standard -a manabiya`で、Heroku Schedulerをmanabiyaアプリにインストールして、CLIを使えるようにする(このコマンドを実行しなくてもブラウザからherokuアプリに行って設定できるんだと思う)
  - herokuログイン、なぜか前にアカウント作ったのにログインできず、パスワード忘れたで送信処理もしたけどメール届かないので、同じメアドで新しくアカウント作った→ログインできるようになった
- herokuのダッシュボードにアクセス。CLIの場合は`heroku addons:open scheduler`でできる。
  - エラーになった： **manabiyaのherokuに権限がないのが理由と思われる**

```bash
heroku addons:open scheduler
 ›   Warning: heroku update available from 7.67.1 to 9.5.0.
 ▸    Couldn't find that add on.
``` 

- その他やったこと
  - heroku CLIのバージョンが古いのでupdateした：`heroku update`

**Comment by Saki-htr** [comment]
heroku の コラボレーターに参加してもらった。
```ruby
> heroku apps
=== Collaborated Apps

 manabiya XXXX@gmail.com 
 tttobira XXXX@gmail.com 
```

**Comment by Saki-htr** [comment]
## herokuにコラボレーター権限もらったので定期実行の設定をしていく

```bash
% heroku addons:create scheduler:standard -a manabiya
Creating scheduler:standard on ⬢ manabiya... free
 To manage scheduled jobs run:
 heroku addons:open scheduler

Created scheduler-corrugated-43890
Use heroku addons:docs scheduler to view documentation
```

```
> heroku addons -a manabiya

 Add-on                                       Plan        Price        Max price State   
 ──────────────────────────────────────────── ─────────── ──────────── ───────── ─────── 
 heroku-postgresql (postgresql-tapered-96931) essential-0 ~$0.007/hour $5/month  created 
  └─ as DATABASE                                                                         
                                                                                         
 papertrail (papertrail-curved-26802)         choklad     free         free      created 
  └─ as PAPERTRAIL                                                                       
  
# schedulerが追加された!                                                                                       
 scheduler (scheduler-corrugated-43890)       standard    free         free      created 
  └─ as SCHEDULER     
```

- herokuスケジューラーのダッシュボードにアクセス

```bash
% heroku addons:open scheduler -a manabiya
```

**Comment by Saki-htr** [comment]
## ここまでやった所で、実行させたいrakeタスクを本番にデプロイしてないとherokuで実行できないことに気づいた

ので、rakeタスクを作り込んでレビュー依頼に持っていって、マージしてから定期実行の設定をherokuに追加したらいいか

**Comment by Saki-htr** [comment]
# rakeタスクの中身を作り込む

- https://github.com/teacherteacher-jp/manabiya/issues/106#issuecomment-2505116705
- 
フィヨルドのこの辺が参考になりそう：https://github.com/fjordllc/bootcamp/blob/e18e8c2e31fc861a9365eeb819ebcbfff8cba4bd/app/notifiers/discord_notifier.rb#L50

## 毎日のお知らせ

```md
近日開催のイベントをおしらせ

<本日(12/2 月)開催>

イベント1のタイトル名
開始時間: 10:00~
詳細: イベント1詳細URL

イベント2のタイトル名
開始時間: 11:00~
詳細: イベント2詳細URL

-------------------------

<明日(12/3 火) 開催>

イベント1のタイトル名
開始時間: 10:00~
詳細: イベント1詳細URL

イベント2のタイトル名
開始時間: 11:00~
詳細: イベント2詳細URL

-------------------------

<明後日(12/4 水) 開催>

イベント1のタイトル名
開始時間: 10:00~
詳細: イベント1詳細URL

イベント2のタイトル名
開始時間: 11:00~
詳細: イベント2詳細URL
```

## 毎週日曜のお知らせ
- 毎週日曜に、次の1週間のイベント情報を通知
- 通知時間： 毎週日曜朝8時
- 内容：次の1週間(月〜日)開催予定のイベント情報

```md 
<来週(12/2 月 ~ 12/8 日)開催のイベントをおしらせ>

イベント1のタイトル名
開始日時: 12/2(月) 03:00 ~
詳細: イベント1詳細URL

イベント2のタイトル名
開始日時: 12/3(火) 10:00 ~
詳細: イベント2詳細URL
```

**Comment by Saki-htr** [comment]
## embedを使うと楽に綺麗に通知内容を作れるので使ってみることに
